// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqM9PA3ML9CozCstcPp0Yfc4OLNHrr-Ck',
    appId: '1:1079703755305:web:478a210190d6b006601a38',
    messagingSenderId: '1079703755305',
    projectId: 'widget-testing-71556',
    authDomain: 'widget-testing-71556.firebaseapp.com',
    storageBucket: 'widget-testing-71556.firebasestorage.app',
    measurementId: 'G-BS3LN7NNEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnss0sCrZXz1U064Tbpp5fK7U5-79rHLQ',
    appId: '1:1079703755305:android:d50b88e3caf40582601a38',
    messagingSenderId: '1079703755305',
    projectId: 'widget-testing-71556',
    storageBucket: 'widget-testing-71556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNko3wlcKWQKFLIR16i1F7YEvFq4ybb0',
    appId: '1:1079703755305:ios:a14a73880ebee083601a38',
    messagingSenderId: '1079703755305',
    projectId: 'widget-testing-71556',
    storageBucket: 'widget-testing-71556.firebasestorage.app',
    iosBundleId: 'com.example.widgetTesting',
  );
}
